version: "3.7"

services:

  influxdb:
    image: influxdb:2.2-alpine
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb2
    ports:
      - "8086:8086"

  data-logger:
    build: data-logger
    restart: always
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_ORG=$INFLUXDB_ORG
      - INFLUXDB_TOKEN=$INFLUXDB_TOKEN
      - INFLUXDB_BUCKET=$INFLUXDB_BUCKET

  grafana:
    image: grafana/grafana-oss:8.5.5
    restart: always
    volumes:
      - grafana:/var/lib/grafana

  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"

volumes:

  grafana:
    external: true

  influxdb:
    external: true
